### ISSUE TITLE
很赞的插件，是否能提供从扩展商店的安装方式？

### ISSUE THREAD

**Issue by lorryrio** [jrainlau/picee#1]
rt

**Comment by jrainlau** [comment]
要用国外的信用卡支付5美元注册开发者，但是我只有国内的信用卡，搞不了。。。

**Comment by jrainlau** [comment]
> 要用国外的信用卡支付5美元注册开发者，但是我只有国内的信用卡，搞不了。。。

搞定了，已经上架到扩展商店，直接搜**Picee**就行~~

**Comment by lorryrio** [comment]
Aha，安装成功了，多谢多谢！～
