### ISSUE TITLE
Upload failed when the path end with '/' 

### ISSUE THREAD

**Issue by qingmei2** [jrainlau/picee#11]
感谢作者提供了这么好的一个工具。 🎉 

反馈一个小问题，在文件路径配置为 “xx/xx/xx/”，即以“/”为末尾时，上传会显示失败，但警告的信息并不准确：

这个是复现步骤：

![image](https://user-images.githubusercontent.com/21142152/59001594-bdcb9b80-8841-11e9-9239-3c04f9cf11cc.png)

上传失败后的警告信息：

![image](https://user-images.githubusercontent.com/21142152/59001612-d8057980-8841-11e9-80b5-f2532f5f796b.png)

希望能够，即使末尾为分隔符 “/” , 也能够忽略该分隔符， 对图片进行上传哈。 ❤️

**Comment by jrainlau** [comment]
感谢反馈，我会尽快修复~

**Comment by jrainlau** [comment]
![image](https://user-images.githubusercontent.com/12172868/59003953-88777b80-884a-11e9-9a11-0244cfafd00c.png)
1.4.2版本修复。

**Comment by qingmei2** [comment]
稳 👍
