### ISSUE TITLE
chrome禁用了怎么解决

### ISSUE THREAD

**Issue by shuwenjunn** [jrainlau/picee#2]
![image](https://user-images.githubusercontent.com/33014124/57346049-b13f1f00-717f-11e9-964f-dae4c3e913e3.png)

**Comment by shuwenjunn** [comment]
![image](https://user-images.githubusercontent.com/33014124/57346291-85706900-7180-11e9-9e73-ac3077784b5d.png)

**Comment by jrainlau** [comment]
看这儿：https://github.com/jrainlau/picee#installation

下载`zip`包并解压之，然后点击“加载已解压的扩展程序”即可。
