### ISSUE TITLE
点击选择图片弹出对话框后会导致插件的窗口消失

### ISSUE THREAD

**Issue by hellwen** [jrainlau/picee#4]
点击选择图片弹出对话框后会导致插件的窗口消失

**Comment by hellwen** [comment]
我的是archlinux系统

**Comment by jrainlau** [comment]
popup类型的插件，失焦的时候会自动消失。但是我在mac和windows下都测试过，弹出文件选择窗口并不会导致失焦。archlinux系统没有测试过呢，或者你试试更新下chrome版本？

**Comment by hellwen** [comment]
可能和操作系统有关系，我是archlinux + i3，chrome已经是新的了。

**Comment by tr15tan** [comment]
ubuntu 16.04 unity 桌面 + 最新chrome也不行，不管是拖拽还是直接打开选择窗口，根本用不了
