### ISSUE TITLE
上传到仓库的图片名称不是图片原始名称

### ISSUE THREAD

**Issue by lewiszlw** [jrainlau/picee#5]
我测试了下，上传本地的github-icon.png，到了仓库变成了github-icon.23lnmsp2ast.png，请问能否保持原有的图片名称？
ps.插件很棒很实用！

**Comment by jrainlau** [comment]
当初搞这个的目的，是因为通过粘贴进来的图片都叫`image.png`，而github的这个接口是不允许上传已存在的同名文件的，故加了个hash在后面。后续我会把加hash弄成可选的，然后添加正确的错误提示

**Comment by lewiszlw** [comment]
👍👍👍

**Comment by jrainlau** [comment]
https://github.com/jrainlau/picee/releases/tag/1.4.0

feat:
1. Copy image url as markdown format is possible.
2. Images on any website could be copied and pasted to Picee.
3. Rename the image with a hash now is optional.

**Comment by lewiszlw** [comment]
这个设置，在每次重新打开时候就重置了，每次需要再去掉勾选，然后上传，较为麻烦，能否保持本次设置呢？

**Comment by jrainlau** [comment]
1.4.1版本修复这个问题。已经发布，正在审核中。
