### ISSUE TITLE
有计划支持端应用吗？

### ISSUE THREAD

**Issue by howel52** [jrainlau/picee#6]
有了 Chrome Extension 后，是否有可能做成 election 类的端应用？

**Comment by jrainlau** [comment]
技术上是完全可以的。核心代码都在`/package`目录下，要移植到 electron 只需要把 `main.js` 里面的 `chrome.notifications` 替换掉就可以。

一开始搞这个插件的时候也想过直接弄成端应用，但觉得太重了没必要，直接浏览器插件轻量又方便。
