### ISSUE TITLE
上传图片后将图片链接复制到剪切板

### ISSUE THREAD

**Issue by IceMimosa** [jrainlau/picee#7]
1. 上传成功后返回图片地址，比如markdown形式的地址。可以采用github raw服务的地址
2. 如果能记录下上传历史就更好了

感谢分享，很棒的插件。😀

**Comment by jrainlau** [comment]
1.3.0 版本已经支持上传历史~

**Comment by jrainlau** [comment]
https://github.com/jrainlau/picee/releases/tag/1.4.0

feat:
1. Copy image url as markdown format is possible.
2. Images on any website could be copied and pasted to Picee.
3. Rename the image with a hash now is optional.
