### ISSUE TITLE
希望可以添加鼠标右键菜单栏上传选项

### ISSUE THREAD

**Issue by Liumxv** [jrainlau/picee#8]
如果想上传现有网站上图片的话 还得先下载保存 
再拖到扩展里 
有些复杂

**Comment by jrainlau** [comment]
https://github.com/jrainlau/picee/releases/tag/1.4.0

feat:
1. Copy image url as markdown format is possible.
2. Images on any website could be copied and pasted to Picee.
3. Rename the image with a hash now is optional.
